theme: jekyll-theme-cayman
title: Boaz Rensenbrink
description: A Professional who is keen to offer ten years of relevant experience and pursues new professional challenges.
descriptionb: Een Professional die graag tien jaar relevante ervaring biedt en nieuwe professionele uitdagingen aangaat.
google_analytics: UA-150421771-1
show_personal_links: true
